spring:
  application:
    name: sample
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.178.71.199:9092
      bindings:
        consumer-stream:
          binder: kafka
          destination: test
          content-type: application/json
          group: ${spring.application.name}Group-input
        producer-stream:
          destination: test
          content-type: application/json
          group: ${spring.application.name}Group-output
          producer:
            partition-key-expression: headers['partitionKey']
#            partitioned: true
#            partition-count: 13
